version: "3"
services:
  todochamp:
    image: "node:10"
    user: "node"
    working_dir: "/app"
    #environment:
    #  - NODE_ENV=production
    volumes:
        - ./:/app
    expose:
      - "8080"
    command: "npm start"