version: "3"
services:
  todochamp:
    image: "node:15" #latest/current not lts 14
    user: "node"
    working_dir: "/app"
    environment:
      - PORT=8080
    volumes:
        - ./:/app
    expose:
      - "8080"
    command: "npm start"